### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by terhuhf** [TerenceFeng/JnF-RE#2]
### Strategies
1. Transfer grid to page-locked memory (with cudaHostAlloc)
    * More research on page-locked memory
2. __shared__ grid within a block
    * Loading arrangement
    * Memory limitation
    * Memory coalescing
3. Concurrent execution
    * Ref: Lec9 slide 61
4. Loop unrolling

### Issues `Solved`
* Sampler for glossy reflective material
    * each has its own sample distribution, which costs huge memory
    * ATTEMPT: to share distribution with others, replace map_to_hemisphere with a mapping function

**Comment by jiangyangmu** [comment]
优化策略
* Cache Data in Shared Memory - 比如 Tiled Matrix Multiplication，本质是减少了读 global memory 的次数，因为矩阵运算需要读同一个元素 n 次，利用 shared memory 可以减少到 n / block_size 次。另外，shared memory 因为有划分成小内存 bank 的概念，所有 bank 可以并行访问，效率倍增。
* Select Instruction Smart  - float 可以比 double 快上 20 ~ 30 倍。Intrinsic Functions 精度略低，但是速度更快。
* Reduce Divergence - 比如 control flow 中的 branch 只依赖于 (threadIdx / warpSize)，一般 warpSize = 32。
* Change Device Limits - cudaDeviceSetLimit()
* Use Unified Memory Model - 如果某段数据在 device 和 host 之间都需要用，使用 UMM 可以大大简化代码，虽然 performance 并不会提高，该复制的还得复制。(UMM require: SM ≥ 3.0, 64-bit linux or windows)
* Pinhole Optimizations
    * Type Conversion - double 常量赋值给 float 变量，C/C++ 标准规定不能把常量优化成 float，要手动加 f 后缀。
